import type { WidgetNode } from "./types";

export interface MetricCardBlueprintProps {
    label: string;
    value: string;
    accent: string;
}

export interface DashboardSmokeBlueprintProps {
    title?: string;
    subtitle?: string;
}

export function createMetricCardBlueprint(
    name: string,
    props: MetricCardBlueprintProps,
): WidgetNode {
    return {
        type: "metric_card",
        name,
        props: {
            label: props.label,
            value: props.value,
            accent: props.accent,
        },
    };
}

export function createDashboardSmokeBlueprint(
    props: DashboardSmokeBlueprintProps = {},
): WidgetNode {
    return {
        type: "dashboard_shell",
        name: "Semantic Dashboard Demo",
        props: {
            x: 80,
            y: 80,
            width: 1180,
            height: 760,
        },
        layout: {
            kind: "column",
            gap: 24,
            padding: 24,
        },
        style: {
            fills: [{ fillColor: "#F4F7FB" }],
            radius: 24,
        },
        children: [
            {
                type: "board",
                name: "Header Section",
                layout: {
                    kind: "column",
                    gap: 8,
                },
                children: [
                    {
                        type: "text",
                        name: "Dashboard Title",
                        props: {
                            text: props.title ?? "Operations Dashboard",
                            fontSize: 28,
                            x: 0,
                            y: 0,
                        },
                    },
                    {
                        type: "text",
                        name: "Dashboard Subtitle",
                        props: {
                            text: props.subtitle ?? "Semantic widget tree generated by MCP",
                            fontSize: 14,
                            x: 0,
                            y: 40,
                        },
                    },
                ],
            },
            {
                type: "board",
                name: "Metrics Row",
                layout: {
                    kind: "row",
                    gap: 16,
                },
                responsive: {
                    compact: {
                        layout: {
                            kind: "column",
                        },
                    },
                },
                children: [
                    createMetricCardBlueprint("Revenue Card", {
                        label: "Revenue",
                        value: "$128K",
                        accent: "#2F6BFF",
                    }),
                    createMetricCardBlueprint("Active Users Card", {
                        label: "Active Users",
                        value: "8.4K",
                        accent: "#19A974",
                    }),
                    createMetricCardBlueprint("NPS Card", {
                        label: "NPS",
                        value: "71",
                        accent: "#FF8A34",
                    }),
                ],
            },
            {
                type: "board",
                name: "Content Row",
                layout: {
                    kind: "row",
                    gap: 16,
                },
                responsive: {
                    compact: {
                        layout: {
                            kind: "column",
                        },
                    },
                },
                children: [
                    {
                        type: "chart_panel",
                        name: "Chart Panel",
                        props: {
                            width: 760,
                            height: 320,
                        },
                        layout: {
                            kind: "column",
                            gap: 16,
                            padding: 20,
                        },
                        style: {
                            fills: [{ fillColor: "#FFFFFF" }],
                            radius: 20,
                        },
                        children: [
                            {
                                type: "text",
                                name: "Chart Title",
                                props: {
                                    text: "Weekly Growth",
                                    fontSize: 18,
                                    x: 0,
                                    y: 0,
                                },
                            },
                            {
                                type: "board",
                                name: "Bars Row",
                                layout: {
                                    kind: "row",
                                    gap: 12,
                                },
                                children: [
                                    {
                                        type: "rectangle",
                                        name: "Bar 1",
                                        props: {
                                            x: 0,
                                            y: 0,
                                            width: 64,
                                            height: 120,
                                        },
                                        style: {
                                            fills: [{ fillColor: "#D7E4FF" }],
                                            radius: 16,
                                        },
                                    },
                                    {
                                        type: "rectangle",
                                        name: "Bar 2",
                                        props: {
                                            x: 0,
                                            y: 0,
                                            width: 64,
                                            height: 180,
                                        },
                                        style: {
                                            fills: [{ fillColor: "#AFC7FF" }],
                                            radius: 16,
                                        },
                                    },
                                    {
                                        type: "rectangle",
                                        name: "Bar 3",
                                        props: {
                                            x: 0,
                                            y: 0,
                                            width: 64,
                                            height: 150,
                                        },
                                        style: {
                                            fills: [{ fillColor: "#7AA4FF" }],
                                            radius: 16,
                                        },
                                    },
                                    {
                                        type: "rectangle",
                                        name: "Bar 4",
                                        props: {
                                            x: 0,
                                            y: 0,
                                            width: 64,
                                            height: 220,
                                        },
                                        style: {
                                            fills: [{ fillColor: "#2F6BFF" }],
                                            radius: 16,
                                        },
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        type: "insights_panel",
                        name: "Insights Panel",
                        props: {
                            width: 340,
                            height: 320,
                        },
                        layout: {
                            kind: "column",
                            gap: 14,
                            padding: 20,
                        },
                        style: {
                            fills: [{ fillColor: "#0E1B2A" }],
                            radius: 20,
                        },
                        children: [
                            {
                                type: "text",
                                name: "Insights Title",
                                props: {
                                    text: "Highlights",
                                    fontSize: 18,
                                    x: 0,
                                    y: 0,
                                },
                            },
                            {
                                type: "text",
                                name: "Insight 1",
                                props: {
                                    text: "Revenue increased 12% week over week",
                                    fontSize: 14,
                                    x: 0,
                                    y: 28,
                                },
                            },
                            {
                                type: "text",
                                name: "Insight 2",
                                props: {
                                    text: "Activation improved after onboarding changes",
                                    fontSize: 14,
                                    x: 0,
                                    y: 56,
                                },
                            },
                            {
                                type: "text",
                                name: "Insight 3",
                                props: {
                                    text: "NPS remains above the quarterly target",
                                    fontSize: 14,
                                    x: 0,
                                    y: 84,
                                },
                            },
                        ],
                    },
                ],
            },
        ],
    };
}
